# Configuração global de eventos do NGINX
events {
    worker_connections 1024;
}

# Bloco principal de configuração HTTP
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Inclui TODAS as configurações de projetos do diretório conf.d
    include /etc/nginx/conf.d/*.conf;
}
